#!/bin/bash
#
# Copyright (C) 2022  David Valin dvalin@redhat.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

device_to_use=""
mount_pnt=""
fs_type=""
valid_fs_type="xfs ext4 ext3 gfs2 gfs"

if [[ $TOOLS_BIN == "" ]]; then
	TOOLS_BIN=$(realpath $(dirname $0))
fi

source ${TOOLS_BIN}/error_codes

usage()
{
	echo "Usage: $1"
	echo "  --fs_type: filesystem to create.  ${valid_fs_type}"
	echo "  --mount_dir: directory to mount to"
	echo "  --device: device to use."
	exit $E_USAGE
}

#
# Verify parameters passed in.
#
validate_data()
{
	if [[ $device_to_use = "" ]]; then
		echo You need to designate a device to use.
		exit $E_GENERAL
	fi
	if [[ ! -e $device_to_use ]]; then
		echo Designated device, $device_to_use, does not exist
		exit $E_GENERAL
	fi
	if [[ $mount_pnt = "" ]]; then
		echo You need to designate a mount point.
		exit $E_GENERAL
	fi
	if [[ $fs_type = "" ]]; then
		echo You need to designate a filesys type.
		exit $E_GENERAL
	fi
}

#
# Define options
#
ARGUMENT_LIST=(
        "device"
        "fs_type"
        "mount_dir"
)

NO_ARGUMENTS=(
        "usage"
)

# read arguments
opts=$(getopt \
    --longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
    --longoptions "$(printf "%s," "${NO_ARGUMENTS[@]}")" \
    --name "$(basename "$0")" \
    --options "h" \
    -- "$@"
)

if [ $? -ne 0 ]; then
        exit
fi
eval set -- "$opts"

while [[ $# -gt 0 ]]; do
	case "$1" in
		--device)
			device_to_use=${2}
			shift 2
		;;
		--fs_type)
			fs_type=${2}
			shift 2
		;;
		--mount_dir)
			mount_pnt=${2}
			mkdir -p "$mount_pnt"
			shift 2
		;;
		--usage)
			usage $0
		;;
		-h)
			usage $0
		;;
		--)
			break;
		;;
		*)
			echo option not found $1
			usage $0
		;;
	esac
done

validate_data

#
# Create the file system.
#
case $fs_type in
	ext3)
		MKFS_OPS="-F"
	;;
	ext4|ext4dev)
		MKFS_OPS="-F"
	;;
	gfs)
		MKFS_OPS="-O -p lock_nolock -j 1"
	;;
	gfs2)
		MKFS_OPS="-O -p lock_nolock -j 1"
	;;
	xfs)
		MKFS_OPS="-f"
	;;
	*)
		echo Error, $fs_type unknown filesystem type
		exit $E_GENERAL
	;;
esac
echo "mkfs -t ${fs_type} ${MKFS_OPS} ${device_to_use}"
mkfs -t ${fs_type} ${MKFS_OPS} ${device_to_use}
if [ $? -ne 0 ]; then
	exit $E_GENERAL
fi
mount ${device_to_use} "${mount_pnt}"
if [ $? -ne 0 ]; then
	exit $E_GENERAL
fi
exit  $E_SUCCESS
