#!/bin/bash

exec_file="./detect_numa"
num_nodes=`lscpu | grep "NUMA node(s)" | grep -Eo "[0-9]+"`
cpu_node=`lscpu | grep -E "NUMA node[0-9]+" | awk '{ print $NF }'`

source "./tests/assert.sh"

# Test Default behavior to output number of NUMA nodes
assert "$exec_file" "$num_nodes"

# Test --node-count flag
assert "$exec_file --node-count" "$num_nodes"

# Test --cpu-list flag outputs CPUs grouped by NUMA node
assert "$exec_file --cpu-list" $cpu_node

# Ensure that the --node flag fails when a NUMA node does not exist
assert_raises "$exec_file --node 9999 --cpu-list" 1

assert_end
