on: push

jobs:
  detect_os_ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Dump /etc/os-release for debug purposes
        run: cat /etc/os-release
      - name: Dump uname -a for debug purposes
        run: uname -a
      - name: Run tests
        run: ./tests/test_detect_os --os ubuntu --os-version 22.04 -c example_configs/supported_os.yml

  detect_os_rhel_ubi:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/python-39:1-126
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install yq/jq
        run: pip3 install yq jq
      - name: Dump /etc/os-release for debug purposes
        run: cat /etc/os-release
      - name: Run tests # Skipping uname since kernel does not change
        run: ./tests/test_detect_os --skip-uname --os rhel --os-version 8.8 -c example_configs/supported_os.yml

