on: push

jobs:
  detect_os_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Dump /etc/os-release for debug purposes
        run: cat /etc/os-release
      - name: Dump uname -a for debug purposes
        run: uname -a
      - name: Run tests
        run: ./tests/test_detect_os --os ubuntu

  detect_os_rhel_ubi:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Dump /etc/os-release for debug purposes
        run: cat /etc/os-release
      - name: Run tests # Skipping uname since kernel does not change
        run: ./tests/test_detect_os --skip-uname --os rhel

